# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-02 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_auto_20190502_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityjobs',
            name='slug',
            field=models.SlugField(default=0, max_length=35),
        ),
        migrations.AlterField(
            model_name='apply',
            name='designation',
            field=models.CharField(max_length=2),
        ),
    ]
