# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_auto_20190502_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityjobs',
            name='slug',
            field=models.SlugField(blank=True, max_length=35),
        ),
    ]
